<?php
/**
 * SmsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  NotifyLk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Notify.lk API
 *
 * Send SMS with Notify.lk
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace NotifyLk;

use \NotifyLk\Configuration;
use \NotifyLk\ApiException;
use \NotifyLk\ObjectSerializer;

/**
 * SmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  NotifyLk
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getStatus
     *
     * Retrieve the account status.
     *
     */
    public function testGetStatus()
    {
    }

    /**
     * Test case for sendSMS
     *
     * Sending SMS to a number from specified sender ID.
     *
     */
    public function testSendSMS()
    {
    }
}
